logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.format_sql: TRACE
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/music_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        formatsql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
